Repository outpost-os/sentry-kernel, pull requests merged in 2024-09, with the labels that each got.

#34 ci: adding reuse check for PR
  .github/workflows/reuse.yml
Labels: ci-cd, enhancement

#35 doc: rdt config, manually set version by now
  .readthedocs.yaml
  doc/concepts/conf.py
Labels: documentation

#36 doc: adding usual badges
  README.md
Labels: documentation

#37 Add reuse badge
  README.md
Labels: documentation

#38 doc: enhanced 'adding new soc' part
  doc/concepts/sw_architecture/bsp.rst
Labels: documentation

#41 SHM: adding sys_shm_get_infos() syscall
  .github/workflows/gnulinux.yml
  .github/workflows/proof.yml
  autotest/src/tests/test_shm.c
  doc/concepts/uapi/syscalls.rst
  doc/concepts/uapi/syscalls/meson.build
  doc/concepts/uapi/syscalls/shm_get_infos.rst
  kernel/include/sentry/managers/memory.h
  kernel/include/sentry/syscalls.h
  kernel/src/arch/asm-generic/handler-svc-lut.c
  kernel/src/managers/memory/memory_shm.c
  kernel/src/syscalls/meson.build
  kernel/src/syscalls/sysgate_shm_get_infos.c
  uapi/include/uapi/types.h
  uapi/include/uapi/uapi.h
  uapi/uapi/syscall.rs
  uapi/uapi/systypes.rs
Labels: api, enhancement

#56 ci: deploy sdist tarball at push-main event
  .github/workflows/sdist.yml
Labels: ci-cd

#55 artifact: in autotest mode, add firmware.hex to install target
  meson.build
Labels: ci-cd

#44 dma: Add support for DMA API: IRQ+assign/startup part
  autotest/src/tests/test_dma.c
  kernel/include/bsp/drivers/dma/gpdma.h
  kernel/src/arch/asm-generic/handler-svc-lut.c
  kernel/src/drivers/dma/stm32-gpdma-dt.c.in
  kernel/src/drivers/dma/stm32-gpdma-dt.h.in
  kernel/src/drivers/dma/stm32u5-gpdma.c
  kernel/src/managers/dma/dma-dt.h.in
  kernel/src/managers/dma/dma.c
  kernel/src/managers/dma/dma.h
  uapi/include/uapi/types.h
  uapi/include/uapi/uapi.h
  uapi/uapi/syscall.rs
  uapi/uapi/systypes.rs
Labels: api, test

#59 asm,cortex-m: Add warning at configure time if soc bus definition is missing
  kernel/include/sentry/arch/asm-cortex-m/meson.build
Labels: bug

#62 mroper: fix Wlimit warning when no shm or device declared
  kernel/src/managers/device/device.c
  kernel/src/managers/memory/memory_shm-dt.c.in
  kernel/src/managers/memory/memory_shm.c
Labels: enhancement

#46 tools: fix parseelf and add dump to stdout support
  tools/parseelf.py
Labels: python

#63 support/meson/version: fix case where there is no tags
  support/meson/version.sh
Labels: bug
