Repository outpost-os/sentry-kernel, pull requests merged in 2025-01, with the labels that each got.

#108 uapi,doc: fix concepts for new C uapi export
  doc/concepts/tests/autotest.rst
  doc/concepts/uapi/syscalls.rst
  doc/concepts/uapi/syscalls/alarm.rst
  doc/concepts/uapi/syscalls/dma_assign_stream.rst
  doc/concepts/uapi/syscalls/dma_resume_stream.rst
  doc/concepts/uapi/syscalls/dma_start_stream.rst
  doc/concepts/uapi/syscalls/dma_suspend_stream.rst
  doc/concepts/uapi/syscalls/dma_unassign_stream.rst
  doc/concepts/uapi/syscalls/exit.rst
  doc/concepts/uapi/syscalls/get_dev_handle.rst
  doc/concepts/uapi/syscalls/get_dma_stream_handle.rst
  doc/concepts/uapi/syscalls/get_random.rst
  doc/concepts/uapi/syscalls/get_shm_handle.rst
  doc/concepts/uapi/syscalls/get_task_handle.rst
  doc/concepts/uapi/syscalls/gpio_get.rst
  doc/concepts/uapi/syscalls/gpio_reset.rst
  doc/concepts/uapi/syscalls/gpio_set.rst
  doc/concepts/uapi/syscalls/gpio_toggle.rst
  doc/concepts/uapi/syscalls/irq_acknowledge.rst
  doc/concepts/uapi/syscalls/irq_disable.rst
  doc/concepts/uapi/syscalls/irq_enable.rst
  doc/concepts/uapi/syscalls/log.rst
  doc/concepts/uapi/syscalls/map.rst
  doc/concepts/uapi/syscalls/pm_clock_set.rst
  doc/concepts/uapi/syscalls/send_ipc.rst
  doc/concepts/uapi/syscalls/send_signal.rst
  doc/concepts/uapi/syscalls/shm_get_infos.rst
  doc/concepts/uapi/syscalls/shm_map.rst
  doc/concepts/uapi/syscalls/shm_set_credential.rst
  doc/concepts/uapi/syscalls/shm_unmap.rst
  doc/concepts/uapi/syscalls/waitforevent.rst
Labels: documentation, enhancement

#111 kernel,driver,busses: enhanced stm32 busses detection in template
  kernel/include/sentry/arch/asm-cortex-m/stm32l4-buses.h.in
Labels: enhancement

#112 stm32,lpuart: remove "DISABLED" from some registers name and fields
  kernel/src/drivers/usart/stm32-lpuart.c
Labels: enhancement

#113 stm32, rcc: enhanced his48 handling
  kernel/src/drivers/clk/stm32-rcc.c.in
  kernel/src/drivers/clk/stm32l4-rcc.h.in
  kernel/src/drivers/clk/stm32u5-rcc.c
  kernel/src/drivers/clk/stm32u5-rcc.h.in
Labels: enhancement

#116 ci,toolchain: adding gcc-14, moving default to gcc-13.2
  .github/workflows/gnulinux.yml
Labels: ci-cd

#117 meson,install: installing dts and dtsi files
  dts/examples/nucleo_l476rg_autotest.dts
  dts/meson.build
  meson.build
Labels: buildsystem:meson
